import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties | any> = {
  background: {
    background: 'radial-gradient(circle at 20% 20%, #2E1065 0%, #0F172A 40%, #020617 100%)',
    minHeight: '100vh',
    width: '100%',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column', // Permitir que las cosas bajen en desktop/mobile
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
    boxSizing: 'border-box',
    padding: '40px 20px',
  },
  glow1: {
    position: 'absolute',
    top: '15%',
    left: '25%',
    width: '350px',
    height: '350px',
    background: 'radial-gradient(circle, rgba(139, 92, 246, 0.25) 0%, rgba(0,0,0,0) 70%)',
    filter: 'blur(40px)',
    pointerEvents: 'none',
  },
  glow2: {
    position: 'absolute',
    bottom: '10%',
    right: '20%',
    width: '400px',
    height: '400px',
    background: 'radial-gradient(circle, rgba(59, 130, 246, 0.2) 0%, rgba(0,0,0,0) 70%)',
    filter: 'blur(50px)',
    pointerEvents: 'none',
  },
  particle: {
    position: 'absolute',
    width: '3px',
    height: '3px',
    backgroundColor: '#A78BFA',
    borderRadius: '50%',
    opacity: 0.6,
    boxShadow: '0 0 8px #C084FC',
  },
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    zIndex: 10,
    boxSizing: 'border-box',
  },
  card: {
    background: 'rgba(255, 255, 255, 0.04)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderRadius: '24px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5), inset 0 1px 1px rgba(255,255,255,0.1)',
    padding: '44px',
    width: '100%',
    maxWidth: '480px',
    boxSizing: 'border-box',
  },
  cardCenter: {
    background: 'rgba(255, 255, 255, 0.04)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    borderRadius: '24px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5), inset 0 1px 1px rgba(255,255,255,0.1)',
    padding: '44px',
    width: '100%',
    maxWidth: '480px',
    textAlign: 'center',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  formTitulo: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#FFFFFF',
    margin: '0 0 10px 0',
  },
  formSubtitulo: {
    fontSize: '14px',
    color: '#94A3B8',
    margin: '0 0 36px 0',
    lineHeight: '1.6',
  },
  confirmTitulo: {
    fontSize: '26px',
    fontWeight: '700',
    color: '#10B981',
    margin: '20px 0 6px 0',
  },
  confirmSubtitulo: {
    fontSize: '15px',
    color: '#94A3B8',
    margin: '0 0 32px 0',
  },
  checkCircle: {
    background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.2) 0%, rgba(5, 150, 105, 0.05) 100%)',
    border: '1px solid rgba(16, 185, 129, 0.3)',
    borderRadius: '50%',
    width: '72px',
    height: '72px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkIcon: {
    width: '36px',
    height: '36px',
    color: '#10B981',
  },
  montoWrapper: {
    marginBottom: '36px',
    textAlign: 'left',
    width: '100%',
  },
  label: {
    display: 'block',
    fontSize: '12px',
    fontWeight: '600',
    color: '#C084FC',
    marginBottom: '10px',
    textTransform: 'uppercase',
    letterSpacing: '0.75px',
  },
  montoRow: {
    display: 'flex',
    gap: '14px',
    alignItems: 'stretch',
    width: '100%',
  },
  select: {
    padding: '16px',
    borderRadius: '14px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    backgroundColor: '#0F172A',
    fontSize: '15px',
    color: '#FFFFFF',
    fontWeight: '600',
    outline: 'none',
  },
  montoInputWrapper: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    borderRadius: '14px',
    padding: '0 18px',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
  },
  montoSymbol: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#64748B',
    marginRight: '10px',
  },
  inputMonto: {
    border: 'none',
    outline: 'none',
    padding: '16px 0',
    width: '100%',
    fontSize: '20px',
    fontWeight: '600',
    color: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  montoBox: {
    background: 'linear-gradient(135deg, rgba(36, 13, 71, 0.6) 0%, rgba(15, 23, 42, 0.6) 100%)',
    borderRadius: '16px',
    padding: '20px 24px',
    width: '100%',
    boxSizing: 'border-box',
    marginBottom: '14px',
    border: '1px solid rgba(139, 92, 246, 0.15)',
  },
  montoLabel: {
    fontSize: '12px',
    color: '#94A3B8',
    margin: '0 0 6px 0',
    textTransform: 'uppercase',
  },
  montoValor: {
    fontSize: '32px',
    fontWeight: '700',
    color: '#FFFFFF',
    margin: 0,
  },
  montoMoneda: {
    fontSize: '18px',
    fontWeight: '500',
    color: '#A78BFA',
  },
  saldoBox: {
    border: '1px dashed rgba(16, 185, 129, 0.3)',
    borderRadius: '14px',
    padding: '14px 24px',
    width: '100%',
    boxSizing: 'border-box',
    marginBottom: '36px',
    backgroundColor: 'rgba(16, 185, 129, 0.04)',
  },
  saldoLabel: {
    fontSize: '13px',
    color: '#94A3B8',
    margin: '0 0 2px 0',
  },
  saldoValor: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#34D399',
    margin: 0,
  },
  btnDepositar: {
    width: '100%',
    padding: '16px',
    borderRadius: '14px',
    border: 'none',
    background: 'linear-gradient(135deg, #7C3AED 0%, #4F46E5 100%)',
    color: '#FFFFFF',
    fontSize: '16px',
    fontWeight: '600',
  },
  btnNuevo: {
    width: '100%',
    padding: '16px',
    borderRadius: '14px',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    color: '#FFFFFF',
    fontSize: '16px',
    fontWeight: '600',
  },
  
  // === ESTILOS PARA LA SECCIÓN DE HISTORIAL DE NOTIFICACIONES SIMULADAS ===
  notifSection: {
    width: '100%',
    maxWidth: '480px',
    marginTop: '40px',
    zIndex: 10,
  },
  notifSeccionTitulo: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#A78BFA',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    marginBottom: '16px',
  },
  notifLista: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  notifItem: {
    background: 'rgba(255, 255, 255, 0.02)',
    border: '1px solid rgba(255, 255, 255, 0.04)',
    borderRadius: '14px',
    padding: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  notifMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  notifItemTitulo: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#FFFFFF',
    margin: 0,
  },
  notifItemMensaje: {
    fontSize: '13px',
    color: '#94A3B8',
    margin: 0,
  },
  notifMontoBox: {
    textAlign: 'right',
  },
  notifMontoValor: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#10B981',
    margin: 0,
  },
  notifMoneda: {
    fontSize: '12px',
    color: '#A78BFA',
    fontWeight: '500',
  }
};