import { CSSProperties } from 'react';

export const estilosNotificacion: Record<string, CSSProperties> = {
  contenedorCampana: {
    position: 'relative',
    display: 'inline-block',
  },
  botonCampana: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    position: 'relative',
    padding: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeContador: {
    position: 'absolute',
    top: '2px',
    right: '2px',
    backgroundColor: '#FF3B30',
    color: '#FFFFFF',
    borderRadius: '50%',
    width: '16px',
    height: '16px',
    fontSize: '10px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1.5px solid #1A0736',
  },
  dropdown: {
    position: 'absolute',
    right: 0,
    marginTop: '12px',
    backgroundColor: '#FFFFFF',
    boxShadow: '0px 8px 24px rgba(0, 0, 0, 0.15)',
    borderRadius: '12px',
    width: '340px',
    zIndex: 1000,
    padding: '16px',
    border: '1px solid #EFEFEF',
  },
  cabeceraDropdown: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: '0 0 12px 0',
    borderBottom: '1px solid #F5F5F5',
    paddingBottom: '8px',
  },
  tituloDropdown: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#1A0736',
  },
  botonLimpiar: {
    background: 'none',
    border: 'none',
    color: '#6366F1',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: '500',
    padding: 0,
  },
  listaNotificaciones: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    maxHeight: '280px',
    overflowY: 'auto',
  },
  itemNotificacion: {
    padding: '10px 4px',
    borderBottom: '1px solid #F9F9F9',
    fontSize: '13px',
    color: '#4A4A4A',
    lineHeight: '1.4',
    textAlign: 'left',
  },
  contenidoTexto: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  // NUEVO: Color morado específico para resaltar los nombres de tus usuarios
  nombreResaltado: {
    color: '#6366F1', 
    fontWeight: '600',
  },
  tiempoTexto: {
    fontSize: '11px',
    color: '#8E8E93',
  },
  textoVacio: {
    fontSize: '14px',
    color: '#8E8E93',
    textAlign: 'center',
    padding: '16px 0',
    margin: 0,
  }
};